name: Train / Test Model

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-validate:
    name: Build, Train, and Validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go (for Dagger)
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Run Dagger Pipeline
        run: cd dagger && go run main.go

      - name: Rename Model File
        run: mv .models/lead_model_lr.pkl .models/model.pkl 

      - name: Upload Model Artifact
        uses: actions/upload-artifact@v4.4.0
        with:
          name: model
          path: ./models/lead_model_lr.pkl

      - name: Run Model Inference Test Action
        uses: lasselundstenjensen/itu-sdse-project-model-validator@main